state/urls.py
# django.urls import path
from django.conf.urls import url
from . import views
app_name='state'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^reportstate/$', views.reportstate, name='reportstate'),
    url(r'^doreport/$', views.doreport, name='doreport'),
]

vcmmanager/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vcm/', include('worker.urls',namespace='worker')),
    url(r'^state/', include('state.urls',namespace='state')),
    #url(r'^admin/', admin.site.urls),
    #url(r'^',include('cert.urls',namespace='cert')),
]
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]
"""

worker/urls.py
# django.urls import path
from django.conf.urls import url
from . import views
app_name='worker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^listvcm/$', views.listvcm,name='listvcm'),
    url(r'^listserver/$', views.listserver, name='listserver'),
    url(r'^applyvcm/$', views.applyvcm, name='applyvcm'),
    url(r'^delvcm/$', views.delvcm, name='delvcm'),
    url(r'^regserver/$', views.regserver, name='regserver'),
]

state/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

worker/models.py
from __future__ import unicode_literals

from django.db import models
from django.forms.models import model_to_dict
# Create your models here.


class Users(models.Model):
    name = models.CharField(max_length=200)
    pwd = models.IntegerField(default=0)


class vcms(models.Model):
    name = models.CharField(max_length=200)
    server = models.CharField(max_length=200)
    busy = models.CharField(max_length=200)


class servers(models.Model):
    name = models.CharField(max_length=200)
    ip = models.CharField(max_length=200, default='')
    sys = models.CharField(max_length=200, default='')
    cpu = models.IntegerField(default=0)
    mem = models.IntegerField(default=0)
    totalInst = models.IntegerField(default=0)
    spec = models.CharField(max_length=300, default='')
    availableInst = models.CharField(max_length=250, default='')
    nance = models.IntegerField(default=0)
    lastreport = models.DateTimeField(default='')


class kmc(models.Model):
    name = models.CharField(max_length=200)
    ip = models.CharField(max_length=200, default='')
    sys = models.CharField(max_length=200, default='')
    cpu = models.IntegerField(default=0)
    mem = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    available = models.IntegerField(default=0)
    nance = models.IntegerField(default=0)
    lastreport = models.DateTimeField(default='')



def records2dict(records, prefix):
    dict = {}
    n = 1
    for rec in records:
        tempdict = {}
        tempkey = '%s%d' % (prefix, n)
        tempdict[tempkey] = model_to_dict(rec,exclude='id')
        dict.update(tempdict)
        n += 1
    return dict

state/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
import json
from worker.models import vcms
from worker.models import servers


def index(request):
    global context
    context = {}
    return render(request, 'state/index.html')


def reportstate(request):
    context = {}
    return render(request, 'state/reportstate.html')


def doreport(request):
    outstr=''
    if request.method == 'POST':
        rawdata= request.POST['jsondata']
        reportdata= json.loads(rawdata)
        for server in reportdata:
            for vm in reportdata[server]:
                oldState = vcms.objects.filter(server=server, name=vm)
                if oldState.count() > 0 and 'busy' in reportdata[server][vm] and reportdata[server][vm]['busy'] != oldState[0].busy:
                    newState = oldState[0]
                    newState.busy = reportdata[server][vm]['busy']
                    outstr += vm
                    newState.save()
    return HttpResponse(outstr, content_type="application/json")
    #return render(request, 'state/reportstate.html',  context)

worker/views.py
from django.http import HttpResponse
import json
from django.shortcuts import render
from worker.models import vcms
from worker.models import servers
from worker.models import records2dict


def index(request):
    global context
    context = {}
    return render(request, 'worker/index.html')


def listvcm(request):
    context = {}
    vcmlist = vcms.objects.all()
    outdict = records2dict(vcmlist, 'vcm')
    outstr = json.dumps(outdict)
    return HttpResponse(outstr, content_type="application/json")


# context['vcmlist'] = vcmlist
# return render(request, 'worker/listvcm.html', context)
# return render(request, 'worker/listvcm.html')


def listserver(request):
    context = {}
    serverlist = servers.objects.all()
    outdict = records2dict(serverlist, 'server')
    outstr = json.dumps(outdict)
    return HttpResponse(outstr, content_type="application/json")


# context['serverlist'] = serverlist
# return render(request, 'worker/listserver.html', context)
# return render(request, 'worker/listserver.html')


def applyvcm(request):
    context = {}
    vcmidle = vcms.objects.filter(busy='idle')
    if vcmidle.count() > 0:
        context['getvcm'] = vcmidle[0].name
        row = vcmidle[0]
        row.busy = 'busy'
        row.save()
    return render(request, 'worker/applyvcm.html', context)


def delvcm(request):
    context = {}
    vcmbusy = vcms.objects.filter(busy='busy')
    if vcmbusy.count() > 0:
        context['getvcm'] = vcmbusy[0].name
        row = vcmbusy[0]
        row.busy = 'idle'
        row.save()
    return render(request, 'worker/delvcm.html', context)


# return render(request, 'worker/delvcm.html')


def regserver(request):
    context = {}
    return render(request, 'worker/regserver.html', context)
    # return render(request, 'worker/regserver.html')

state/templates/state/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>VCMMANAGER</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********vcm manager test***********</li>
<a href="http://127.0.0.1:8000/state/">listoption</a>
<a href="http://127.0.0.1:8000/state/reportstate">reportstate</a>
</body>
</html>

state/templates/state/reportstate.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CMS</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********CMS test***********</li>
<form name="openfile" action={% url 'state:doreport' %} method="POST">
    {% csrf_token %}
    file:<input type="file" name="jsonfile" ><br>
    <textarea name="jsondata" id="json_data" cols="45" rows="5">{{ json_data }}</textarea>
    <input type="submit">
</form>
</body>
</html>

worker/templates/worker/applyvcm.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CMS</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********CMS test***********</li>
{{getvcm}}
</body>
</html>

worker/templates/worker/delvcm.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CMS</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********CMS test***********</li>
{{getvcm}}
</body>
</html>

worker/templates/worker/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>VCMMANAGER</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********vcm manager test***********</li>
<a href="http://127.0.0.1:8000/vcm/">listoption</a>
<a href="http://127.0.0.1:8000/vcm/listvcm">listvcm</a>
<a href="http://127.0.0.1:8000/vcm/listserver">listserver</a>
<a href="http://127.0.0.1:8000/vcm/applyvcm">applyvcm</a>
<a href="http://127.0.0.1:8000/vcm/delvcm">delvcm</a>
<a href="http://127.0.0.1:8000/vcm/regserver">regserver</a>
</body>
</html>

worker/templates/worker/listserver.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CMS</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********CMS test***********</li>
{{serverlist}}
</body>
</html>

worker/templates/worker/listvcm.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CMS</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********vcmlist test***********</li>
{{vcmlist}}
</body>
</html>

worker/templates/worker/regserver.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CMS</title>
    <script type="text/javascript">
    <!--
        function MM_jumpOperation(targ,selObj,restore) {//v3.0
            eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
            if(restore) selObj.selectedIndex=0;
        }
    //-->
    </script>
</head>
<body>
<li>***********CMS test***********</li>
<form name="login" action={% url 'cert:certlogin' %} method="POST">
    User Name:<input type="text" name="username"><br>
    Password:<input type="password" name="passwd"><br>
    <input type="submit" value="login">
</form>
</body>
</html>